#pragma once
#ifndef USER_FLAG
#define USER_FLAG

#include "PacketFlags.hpp"

#define MAKE_USER_SEND_PACKET_FLAG(flagName, value) namespace FlagInstances{ const static UserSendPacketFlag flagName {value, #flagName}; } const static int flagName = value
#define MAKE_USER_RECV_PACKET_FLAG(flagName, value) namespace FlagInstances{ const static UserRecvPacketFlag flagName {value, #flagName}; } const static int flagName = value

MAKE_FLAG_COLLECTION_BODY(UserSendPacketFlag)
//以下開始註冊封包Opcode Flag

//對應Client的WvsContext::OnPacket

MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTransferChannel, 0x11);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnInventoryOperation, 0x45);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnInventoryGrow, 0x46);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStatChanged, 0x47);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTemporaryStatSet, 0x48);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTemporaryStatReset, 0x49);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnForcedStatSet, 0x4A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnForcedStatReset, 0x4B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnChangeSkillRecordResult, 0x4C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnChangeStealMemoryResult, 0x4D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserDamageOnFallingCheck, 0x4E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPersonalShopBuyCheck, 0x4F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMobDropMesoPickup, 0x50);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBreakTimeFieldEnter, 0x51);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRuneActSuccess, 0x52);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSkillUseResult, 0x54);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnExclRequest, 0x55);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGivePopularityResult, 0x56);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterInfo, 0x6F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPartyResult, 0x70);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPartyMemberCandidateResult, 0x71);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUrusPartyMemberCandidateResult, 0x72);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPartyCandidateResult, 0x73);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIntrusionFriendCandidateResult, 0x75);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIntrusionLobbyCandidateResult, 0x76);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnExpedtionResult, 0x78);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUrusPartyResult, 0x74);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGuildResult, 0x7C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGuildRequest, 0x7B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAllianceResult, 0x7D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFriendResult, 0x79);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStarFriendResult, 0x7A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTownPortal, 0x7E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBroadcastMsg, 0x7F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMessage, 0x57);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMemoResult, 0x58);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMapTransferResult, 0x59);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAntiMacroResult, 0x5A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAntiMacroBombResult, 0x5B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnQuestClear, 0x62);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnClaimResult, 0x5D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetClaimSvrAvailableTime, 0x5E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnClaimSvrStatusChanged, 0x5F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStarPlanetUserCount, 0x60);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEntrustedShopCheckResult, 0x63);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIncubatorResult, 0x81);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIncubatorHotItemResult, 0x82);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnShopScannerResult, 0x83);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnShopLinkResult, 0x84);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAuctionResult, 0x89);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAuctionMessage, 0x79);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCashPetSkillSettingResult, 0x8B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCashLookChangeResult, 0x8C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCashPetDyeingResult, 0x8D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetTamingMobInfo, 0x61);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSkillLearnItemResult, 0x64);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSkillResetItemResult, 0x65);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAbilityResetItemResult, 0x66);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnExpConsumeItemResult, 0x67);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnExpItemGetResult, 0x68);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharSlotIncResult, 0x69);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPendantSlotIncResult, 0x131);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharRenameResult, 0x6A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGatherItemResult, 0x6B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSortItemResult, 0x6C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetWeekEventMessage, 0x8E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetPotionDiscountRate, 0x8F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnImitatedNPCData, 0x92);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnLimitedNPCDisableInfo, 0x94);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMarriageRequest, 0x85);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMarriageResult, 0x86);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWeddingGiftResult, 0x87);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNotifyMarriedPartnerMapTransfer, 0x88);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMacroSysDataInit, 0x1BE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBridleMobCatchFail, 0x90);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMonsterBookSetCard, 0x95);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMonsterBookSetCover, 0x96);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnHourChanged, 0x97);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMiniMapOnOff, 0x98);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnConsultAuthkeyUpdate, 0x99);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnClassCompetitionAuthkeyUpdate, 0x9A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWebBoardAuthkeyUpdate, 0x9B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSessionValue, 0x9C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFieldValue, 0x9F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPartyValue, 0x9D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFieldSetVariable, 0x9E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBonusExpRateChanged, 0xA0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyChartResult, 0xA1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyInfoResult, 0xA2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyResult, 0xA3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyJoinRequest, 0xA4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyJoinRequestResult, 0xA5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyJoinAccepted, 0xA6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyPrivilegeList, 0xA7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyFamousPointIncResult, 0xA8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilyNotifyLoginOrLogout, 0xA9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilySetPrivilege, 0xAA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFamilySummonRequest, 0xAB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNotifyLevelUp, 0xAC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNotifyWedding, 0xAD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNotifyJobChange, 0xAE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetBuyEquipExt, 0xAF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnScriptProgressMessageBySoul, 0xB1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnScriptProgressMessage, 0xB2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnScriptProgressItemMessage, 0xB3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStaticScreenMessage, 0xB4);
//NoticeQuestProgress::OffStaticScreenMessage, 0xB5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWeatherEffectNotice, 0xB6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWeatherEffectNoticeY, 0xB7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnProgressMessageFont, 0xB8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDataCRCCheckFailed, 0xB9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnShowSlotMessage, 0xBA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetPassenserRequest, 0xB0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWildHunterInfo, 0xBB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnZeroInfo, 0xBC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnZeroWP, 0xBD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnZeroInfoSubHP, 0xBE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCreateUAdvanture, 0xBF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_ClearAnnouncedQuest, 0xC0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnResultInstanceTable, 0xC1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCoolTimeSet, 0xC2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnItemPotChange, 0xC3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetItemCoolTime, 0xC4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetAdDisplayInfo, 0xC5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetMapleStyleInfo, 0xCB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetCoordinationContestInfo, 0x139);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetAdDisplayStatus, 0xC6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetSonOfLinkedSkillResult, 0xC7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetBuyLimitCount, 0xCC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnResetBuyLimitCount, 0xCD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUpdateUIEventListInfo, 0xCE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDojangRankingResult, 0xCF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnHalloweenCandyRankingResult, 0x10A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_ReplaceSkills, 0xD3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnResultStealSkillList, 0x53);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnShutdownMessage, 0xD4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStartNavigation, 0xD5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFunckeySetByScript, 0xD6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterPotentialSet, 0xD7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterPotentialReset, 0xD8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterHonorExp, 0xD9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterHonorGift, 0xE0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAswanResult, 0xDC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReadyForRespawn, 0xDD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReadyForRespawnByPoint, 0xDE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OpenReadyForRespawnUI, 0xDF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCrossHunterCompleteResult, 0xE1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCrossHunterShopResult, 0xE2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetCashItemNotice, 0xE3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetSpecialCashItem, 0xE4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnShowEventNotice, 0xE5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetMiracleTimeInfo, 0xF2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetGachaponFeverTimeInfo, 0x112);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBoardGameResult, 0xE6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnYutGameResult, 0xE7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnValuePackResult, 0xE8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_SetExclRequestSent, 0xEA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNaviFlyingResult, 0xE9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCheckWeddingExResult, 0xEB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBingoResult, 0xEC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBingoCassandraResult, 0xED);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUpdateVIPGrade, 0xEE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMesoRangerResult, 0xEF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetMaplePoint, 0xF0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnHyperSkillResetResult, 0xF3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReceiveHyperStatSkillResetResult, 0x19A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReturnEffectConfirm, 0xF9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReturnEffectModified, 0xFA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMemorialCubeModified, 0xFE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDressUpInfoModified, 0xFF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGetServerTime, 0xF4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGetCharacterPosition, 0xF5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMemorialCubeResult, 0xFD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnChangeSoulCollectionResult, 0x12E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSelectSoulCollectionResult, 0x12F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBlackCubeResult, 0xFC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWhiteAddtionalCubeResult, 0xFB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnActionBarResult, 0x106);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetFixDamage, 0xF7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnResetOnStateForOnOffSkill, 0x101);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetOffStateForOnOffSkill, 0x102);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAvatarPackTest, 0x104);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEvolvingResult, 0x105);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIssueReloginCookie, 0x103);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGetRewardResult, 0x10B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMentoring, 0x10C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGetLotteryResult, 0x10D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCheckProcessResult, 0x10E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCompleteNpcSpeechSuccess, 0x10F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCompleteSpecialCheckSuccess, 0x110);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAvatarMegaphoneRes, 0x113);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetAvatarMegaphone, 0x114);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnClearAvatarMegaphone, 0x115);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRequestEventList, 0x116);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnLikePoint, 0x117);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSignErrorAck, 0x118);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAskAfterErrorAck, 0x119);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEventNameTag, 0x11A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAcquireEventNameTag, 0x11B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnJobFreeChangeResult, 0x11C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEventLotteryOpen, 0x11D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEventLotteryResult, 0x11E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnScreenMsg, 0x126);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTradeBlockForSnapShot, 0x127);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnLimitGoodsNoticeResult, 0x128);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMonsterBattleSystemResult, 0x129);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMonsterBattleCombatResult, 0x12A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUniverseBossPossible, 0x12B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUniverseBossImpossible, 0x12C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCashShopPreviewInfo, 0x12D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMasterPieceReward, 0x130);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBossArenaMatchSuccess, 0x132);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBossArenaMatchFail, 0x133);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBossArenaMatchRequestDone, 0x134);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserSoulMatching, 0x135);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCatapultUpgradeSkill, 0x136);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCatapultResetSkill, 0x137);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPartyQuestRankingResult, 0x138);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnWorldTransferResult, 0x13A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTrunkSlotIncResult, 0x13B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNotifyWorldTransferHelper, 0x13E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEliteMobWMI, 0x13C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRandomPortalNotice, 0x13D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFriendTowerRankResult, 0x141);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTopTowerRankResult, 0x140);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTowerResultUIOpen, 0x142);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMannequinResult, 0x143);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIronBoxPacket, 0x144);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCreateKoreanJumpingGame, 0x145);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCreateSwingGame, 0x146);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUpdateMapleTVShowTime, 0x148);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReturnToTitle, 0x149);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReturnToCharacterSelect, 0x14A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFlameWizardFlameWalkEffect, 0x14B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFlameWizardFlareBlink, 0x14C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSummonedAvatarSync, 0x14D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCashShopEventInfo, 0x17C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBlackList, 0x17D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUIStarPlanetMiniGameResult, 0x183);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUIStarPlanetTrendShop, 0x184);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUIStarPlanetMiniGameQueue, 0x185);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenUITest, 0x17E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnScrollUpgradeFeverTime, 0x180);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTextEquipInfo, 0x181);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTextEquipUIOpen, 0x182);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStarPlanetRoundInfo, 0x187);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStarPlanetResult, 0x188);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBackSpeedCtrl, 0x189);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetMazeArea, 0x18A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterBurning, 0x18B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBattleStatCoreInfo, 0x18C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBattleStatCoreAck, 0x18D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGachaponTestResult, 0x18E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMasterPieceTestResult, 0x18F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRoyalStyleTestResult, 0x190);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBeautyCouponTestResult, 0x191);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNickSkillExpired, 0x192);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRandomMissionResult, 0x193);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnItemCollectionResult, 0x196);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCheckCollectionCompleteResult, 0x197);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnItemCollectionList, 0x198);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_On12thTresureResult, 0x194);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_On12thTresureBuff, 0x195);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReceiveToadsHammerRequestResult, 0x199);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetAccountInfo, 0x111);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnInventoryOperationResult, 0x19B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGetSavedUrusSkill, 0x19C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCharacterModified, 0x1A2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetRolePlayingCharacterInfo, 0x19D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMVPAlarm, 0x19E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTowerChairSettingResult, 0x1A0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMonsterCollectionResult, 0x1A3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNeedClientResponse, 0x19F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTradeKingShopItem, 0x1A1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTradeKingShopRes, 0x1A4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlatFormarEnterResult, 0x1A7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlatFormarOxyzen, 0x1A8);
//InvasionSupportMan::OnInvasionSupportStateChange, 0x10D)
//InvasionSupportMan::OnInvasionSupportAttackResult, 0x10E)
//InvasionSupportMan::OnBossKillResult, 0x10F)
//InvasionSupportMan::OnInvasionSupportSettingResult, 0x110)
//InvasionSupportMan::OnInvasionElapsedTime, 0x111)
//InvasionSupportMan::OnInvasionSystemMsg, 0x112)
//CraftResultDialog::CraftResultDialogEntry, 0x1AF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnChewChewShop, 0x1B3);
//WvsContext::OnPacket 已知部分結束

MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnMakeEnterFieldPacket, 0x21C);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnMakeLeaveFieldPacket, 0x21D);

//對應Client的UserCommon::OnPacket
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnChat, 0x21E);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnADBoard, 0x220);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnMiniRoomBalloon, 0x221);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_SetConsumeItemEffect, 0x222);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_ShowItemUpgradeEffect, 0x223);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_ShowItemReleaseEffect, 0x227);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_ShowItemUnreleaseEffect, 0x22A);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_ShowItemLuckyItemEffect, 0x22B);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_ShowItemOptionChangeEffect, 0x22E);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_ShowItemSkillSocketUpgradeEffect, 0x225);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnInGameCubeResult, 0x230);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnHitByUser, 0x233);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnDotByUser, 0x234);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnResetAllDot, 0x235);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnDamageByUser, 0x236);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnTeslaTriangle, 0x237);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnFollowCharacter, 0x239);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnShowPQReward, 0x23A);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetOneTimeAction, 0x23B);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnMakingSkillResult, 0x23C);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetMakingMeisterSkillEff, 0x23D);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnGatherResult, 0x23E);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnUserExplode, 0x23F);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnUserHitByCounter, 0x240);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnPyramidLethalAttack, 0x241);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnWaitQueueResponse, 0x243);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnMixerResult, 0x244);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnCategoryEventNameTag, 0x246);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetDamageSkin, 0x247);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetPremiumDamageSkin, 0x248);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetSoulEffect, 0x249);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSitResult, 0x24A);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnStarPlanetPointInfo, 0x255);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnStarPlanetAvatarLookSet, 0x256);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnTossedByMobSkill, 0x257);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnBattleAttackHit, 0x258);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnFreezeHotEventInfo, 0x25A);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnEventBestFriendInfo, 0x25B);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetRepeatOneTimeAction, 0x25C);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetReplaceMoveAction, 0x25D);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetActiveEmoticonItem, 0x260);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnCreatePsychicLock, 0x261);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnRecreatePathPsychicLcok, 0x262);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnReleasePsychicLock, 0x263);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnReleasePsychicLockMob, 0x264);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnCreatePsychicArea, 0x265);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnReleasePsychicArea, 0x266);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnRWZeroBunkerMobBind, 0x267);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnBeastFormWingOnOff, 0x268);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnSetMesoChairCount, 0x269);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnRefreshNameTagMark, 0x26C);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_OnStigmaEffect, 0x26D);

//UserCommon::OnPetPacket
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnMakeEnterFieldPacket, 0x26E);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnMakeEnterFieldPacket2, 0x277);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnMove, 0x26F);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnAction, 0x270);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnActionSpeak, 0x271);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnNameChanged, 0x272);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnActionCommand, 0x278);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnLoadExceptionList, 0x273);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnHueChanged, 0x274);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Pet_OnModified, 0x275);

//UserCommon::OnDragonPacket
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Dragon_OnMakeEnterFieldPacket, 0x279);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Dragon_OnMove, 0x27A);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Dragon_OnMakeLeaveFieldPacket, 0x27B);

//UserCommon::OnAndroidPacket
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Android_OnMakeEnterFieldPacket, 0x27D);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Android_OnMove, 0x27E);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Android_OnAndroidSet, 0x27F);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Android_OnModified, 0x280);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_Android_OnMakeLeaveFieldPacket, 0x281);

//UserCommon::OnFoxManPacket
MAKE_USER_SEND_PACKET_FLAG(UserCommon_FoxMan_OnMakeEnterFieldPacket, 0x282);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_FoxMan_OnMove, 0x283);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_FoxMan_OnExclResult, 0x284);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_FoxMan_OnShowChangeEffect, 0x285);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_FoxMan_OnModified, 0x286);
//0x287 for fox man leave field packet?

//UserCommon::OnSkillPetPacket
MAKE_USER_SEND_PACKET_FLAG(UserCommon_SkillPet_OnMakeEnterFieldPacket, 0x288); //not sure
MAKE_USER_SEND_PACKET_FLAG(UserCommon_SkillPet_OnMove, 0x289);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_SkillPet_OnAction, 0x28A);
MAKE_USER_SEND_PACKET_FLAG(UserCommon_SkillPet_OnState, 0x28B);
//Client的UserCommon::OnPacket已知結束

//對應Client的UserRemote::OnPacket
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnMove, 0x295);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetActivePortableChair, 0x2A6);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnAvatarModified, 0x2A7);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetTemporaryStat, 0x2A9);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetCustomRiding, 0x2A4);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnResetTemporaryStat, 0x2AA);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnGuildNameChanged, 0x2AC);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnGuildMarkChanged, 0x2AD);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnPvPTeamChanged, 0x2AE);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnReceiveHP, 0x2AB);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnUpdatePvPHPTag, 0x2B0);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnDragonGlide, 0x2B1);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnKeyDownAreaMovePath, 0x2B2);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnLaserInfoForRemote, 0x2B3);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnKaiserColorOrMorphChange, 0x2B4);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnIntrusion, 0x2B8);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnZeroLastAssistState, 0x2B9);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnScouterMaxDamageUpdate, 0x2C2);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnStigmaDeliveryResponse, 0x2C3);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnMeleeAttack, 0x296);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnShootAttack, 0x297);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnMagicAttack, 0x298);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnBodyAttack, 0x299);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSkillPrepare, 0x29A);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnMovingShootAttackPrepare, 0x29B);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSkillCancel, 0x29C);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnHit, 0x29D);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnEmotion, 0x29E);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnAndroidEmotion, 0x29F);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetMonkeyEffectItem, 0x2A0);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetActiveNickItem, 0x2A1);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetDefaultWingItem, 0x2A2);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetKaiserTransformItem, 0x2A3);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnShowUpgradeTombEffect, 0x2A5);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnEffect, 0x2A8);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnThrowGrenade, 0x2CC);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnDestroyGrenade, 0x2B5);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetMoveGrenade, 0x2BA);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnGatherActionSet, 0x2AF);
MAKE_USER_SEND_PACKET_FLAG(User_OnSetItemAction, 0x2B6);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnZeroTag, 0x2B7);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnSetCustomizeEffect, 0x2BB);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnRuneStoneAction, 0x2BC);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnKinesisPsychicEnergyShieldEffect, 0x2BD);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnDragonAction, 0x2BE);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnDragonBreathEarthEffect, 0x2BF);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnReleaseRWGrab, 0x2C0);
MAKE_USER_SEND_PACKET_FLAG(UserRemote_OnRWMultiChargeCancelRequest, 0x2C1);

//對應Client的UserLocal::OnPacket
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEmotion, 0x2CD); //Local & Common 共用同一個Func
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAndroidEmotion, 0x2CE); //Local & Common 共用同一個Func
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEffect, 0x2CF); //Local & Common 共用同一個Func
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTeleport, 0x2D0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMesoGive_Succeeded, 0x2D2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMesoGive_Failed, 0x2D3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnQuestResult, 0x2D4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNotifyHPDecByField, 0x2D5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserPetSkillChanged, 0x2D6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSkillCooltimeSet, 0x3AD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSkillCooltimeSetM, 0x386);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSkillCooltimeReduce, 0x32D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBalloonMsg, 0x2D7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlayEventSound, 0x2D8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlayMinigameSound, 0x2D9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMakerResult, 0x2DA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenConsultBoard, 0x2DC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenUI, 0x2DD);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCloseUI, 0x2DE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenUIWithOption, 0x2DF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenWebUI, 0x2E0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBagItemUseResult, 0x2FB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetDirectionMode, 0x2E1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetInGameDirectionMode, 0x2E2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetStandAloneMode, 0x2E3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnHireTutorById, 0x2E6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnHireTutor, 0x2E4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTutorMsg, 0x2E5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetPartner, 0x2E7);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetPartnerAction, 0x2E8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetPartnerForceFlip, 0x2E9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSwitchRP, 0x2EA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnModComboResponse, 0x2EB);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIncComboResponseByComboRecharge, 0x2EC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRadioSchedule, 0x2ED);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenSkillGuide, 0x2EE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnNoticeMsg, 0x2EF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnChatMsg, 0x2F0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetUtilDlg, 0x2F1);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBuffzoneEffect, 0x2F2);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTimeBombAttack, 0x2F3);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnExplosionAttack, 0x2F4);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPassiveMove, 0x2F5);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFollowCharacterFailed, 0x2F6);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_UICreatePremiumAdventurerResult, 0x2F8);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGatherRequestResult, 0x2F9);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRuneStoneUseAck, 0x2FA);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRandomTeleportKey, 0x2FC);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnInGameDirectionEvent, 0x2FE);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMedalReissueResult, 0x2FF);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDodgeSkillReady, 0x300);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRemoveMicroBuffSkill, 0x301);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnVideoByScript, 0x302);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRewardMobListResult, 0x304);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIncJudgementStackResponse, 0x305);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIncCharmByCashPRMsg, 0x306);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetBuffProtector, 0x307);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIncLarknessResponse, 0x308);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnB2BodyResult, 0x315);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDetonateBomb, 0x309);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetDressChanged, 0x30D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAggroRankInfoName, 0x30A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSeverAckMobZoneStateChange, 0x30E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDeathCountInfo, 0x30B);
//MAKE_USER_PACKET_FLAG(UserLocal_OnDeathCountInfo, 0x30C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRandomEmotion, 0x311);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetFlipTheCoinEnabled, 0x312);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTrickOrTreatResult, 0x313);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGiantPetBuff, 0x314);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetDead, 0x316);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenUIOnDead, 0x317);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnExpiredNotice, 0x318);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDoLotteryUI, 0x319);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRouletteStart, 0x31A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSitOnTimeCapsule, 0x31B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSitOnDummyPortableChair, 0x31C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFinalAttackRequest, 0x320);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetGun, 0x321);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetAmmo, 0x322);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCreateGun, 0x323);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnClearGun, 0x324);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnResultShootAttackInFPSMode, 0x325);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMirrorDungeonEnterFail, 0x326);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMirrorDungeonUnitCleared, 0x327);
//WvsContext::RegisterMirrorDungeonBoss, 0x328);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMirrorDungeonRecord, 0x329);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenURL, 0x32A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnZeroCombatRecovery, 0x32B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMirrorStudyUIOpen, 0x32C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMirrorReadingUIOpen, 0x32E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnZeroLevelUpAlram, 0x330);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnForceSummonedRemove, 0x333);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMonsterBattleCapture, 0x336);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserCtrlMobSkill_QPush, 0x32F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserCtrlMobSkill_QPop, 0x331);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserCtrlMobSkill_Fail, 0x332);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserRespawn, 0x334);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserCtrlMobSkill_ForcedPop, 0x335);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnIsUniverse, 0x337);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPortalGroup, 0x338);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetMovable, 0x339);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserCtrlMobSkill_PushCoolTime, 0x33A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMoveParticleEff, 0x33B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDoActiveEventSkillByScript, 0x33C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnMoveToContentsCannotMigrate, 0x340);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlayAmbientSound, 0x341);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStopAmbientSound, 0x342);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCameraMode, 0x343);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSpotlightToCharacter, 0x346);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFlameWizardElementFlameSummon, 0x344);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBossPartyCheckDone, 0x347);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFreeLookChangeUIOpen, 0x348);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFreeLookChangeSuccess, 0x349);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGrayBackground, 0x34A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnGetNpcCurrentAction, 0x379);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCameraRotation, 0x37A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCameraSwitch, 0x37B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserSetFieldFloating, 0x37D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnAddPopupSay, 0x37E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnJaguarSkill, 0x380);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnActionLayerRelmove, 0x381);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_SendClientResolution, 0x382);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserBonusAttackRequest, 0x383);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserRandAreaAttackRequest, 0x384);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnJaguarActive, 0x385);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetCarryReactorInfo, 0x387);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnReactorSkillUseRequest, 0x388);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnOpenBattlePvPChampSelectUI, 0x389);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnBattlePvPItemDropSound, 0x38A);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetMesoCountByScript, 0x38B);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlantPotClickResult, 0x38C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnPlantPotEffect, 0x38D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRoyalGuardAttack, 0x38F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDoActivePsychicArea, 0x390);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnEnterFieldPsychicInfo, 0x391);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnLeaveFieldPsychicInfo, 0x392);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnTouchMeStateResult, 0x393);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnFieldScoreUpdate, 0x394);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUrusReusltUIOpen, 0x395);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnCreateAreaDotInfo, 0x399);
//CameraCtrl::Network::OnPacket, 0x37C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnSetSlowDown, 0x39C);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnRegisterExtraSkill, 0x39D);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnResWarriorLiftMobInfo, 0x39E);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnUserRenameResult, 0x39F);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnDamageSkinSaveResult, 0x3A0);
MAKE_USER_SEND_PACKET_FLAG(UserLocal_OnStigmaRemainTime, 0x3A1);

MAKE_USER_SEND_PACKET_FLAG(User_OnNpcShopItemList, 0x56F);
MAKE_USER_SEND_PACKET_FLAG(User_OnNpcShopRequest, 0x570);

MAKE_USER_SEND_PACKET_FLAG(User_OnFuncKeyMapped, 0x614);
//結束Opcode Flag註冊
FLAG_COLLECTION_BODY_END

//Start Recv
MAKE_FLAG_COLLECTION_BODY(UserRecvPacketFlag)
MAKE_USER_RECV_PACKET_FLAG(User_OnUserTransferFieldRequest, 0xB3);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserTransferChannelRequest, 0xB4);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserMigrateToCashShopRequest, 0xB9);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserMoveRequest, 0xC4);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserAttack_MeleeAttack, 0xC9);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserAttack_ShootAttack, 0xCA);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserAttack_MagicAttack, 0xCB);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserAttack_BodyAttack, 0xCC);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserAttack_AreaDot, 0xCD);
MAKE_USER_RECV_PACKET_FLAG(User_OnFullTrueDamaged, 0xCF); //UserLocal::SetFullTrueDamaged
MAKE_USER_RECV_PACKET_FLAG(User_OnBanMapByMobRequest, 0xE1); //UserLocal::SendBanMapByMobRequest
MAKE_USER_RECV_PACKET_FLAG(User_OnSelectNpc, 0xE3);
MAKE_USER_RECV_PACKET_FLAG(User_OnScriptMessageAnswer, 0xE5);
MAKE_USER_RECV_PACKET_FLAG(User_OnShopRequest, 0xE6);
//MAKE_USER_RECV_PACKET_FLAG(User_OnRetOnVideoByScript, 0xE5); //UserLocal::RetOnVideoByScript
MAKE_USER_RECV_PACKET_FLAG(User_OnFinalAttackRequestPacket, 0xED); //UserLocal::SendFinalAttackRequestPacket
MAKE_USER_RECV_PACKET_FLAG(User_OnUserChat, 0xD1);
MAKE_USER_RECV_PACKET_FLAG(User_OnRequestUpgradeTombEffect, 0xDE); //UserLocal::RequestUpgradeTombEffect
MAKE_USER_RECV_PACKET_FLAG(Auction_RegisterItem, 0xF3); //Auction::RegisterItem
MAKE_USER_RECV_PACKET_FLAG(User_OnUserChangeSlotRequest, 0xF7);
MAKE_USER_RECV_PACKET_FLAG(User_OnStatChangeItemUseRequest, 0xFC);
MAKE_USER_RECV_PACKET_FLAG(User_OnStatChangeItemCancelRequest, 0xFD);
MAKE_USER_RECV_PACKET_FLAG(User_OnItemUpgradeRequest, 0x11D);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserSkillUpRequest, 0x13E);
MAKE_USER_RECV_PACKET_FLAG(User_OnUserSkillUseRequest, 0x13F); //UserLocal::SendSkillUseRequest
MAKE_USER_RECV_PACKET_FLAG(User_OnUserSkillCancelRequest, 0x140);
MAKE_USER_RECV_PACKET_FLAG(User_OnActivatePetRequest, 0x148);
MAKE_USER_RECV_PACKET_FLAG(User_OnQuestRequest, 0x154);
MAKE_USER_RECV_PACKET_FLAG(User_OnSendClientResolution, 0x165); //UserLocal::SendClientResolution
MAKE_USER_RECV_PACKET_FLAG(User_OnUpdateLapidification, 0x179); //UserLocal::SendUpdateLapidification

MAKE_USER_RECV_PACKET_FLAG(AffectedArea_OnAffectedAreaCreated, 0x184); //AffectedAreaPool::OnAffectedAreaCreated
MAKE_USER_RECV_PACKET_FLAG(AffectedArea_RemoveAffectedArea, 0x185); //AffectedAreaPool::RemoveAffectedArea
MAKE_USER_RECV_PACKET_FLAG(BattleRpsGame_OnEnter, 0x19A); //BattleRpsGameDlg::OnEnter
MAKE_USER_RECV_PACKET_FLAG(AffectedArea_SendRemoveAffectedAreaSkill, 0x229); //AffectedAreaPool::SendRemoveAffectedAreaSkill

MAKE_USER_RECV_PACKET_FLAG(User_OnTempAct, 0x1A9); //UserLocal::SetTempAct
MAKE_USER_RECV_PACKET_FLAG(User_OnKeyDownAreaMovePathFlush, 0x181); //UserLocal::KeyDownAreaMovePathFlush
MAKE_USER_RECV_PACKET_FLAG(User_OnUpdateZeroTagCoolTimeOut, 0x18D); //UserLocal::UpdateZeroTagCoolTimeOut
MAKE_USER_RECV_PACKET_FLAG(User_OnFuncKeyMappedModified, 0x1B6);
MAKE_USER_RECV_PACKET_FLAG(User_OnRequestIncCombo, 0x1CE); //UserLocal::RequestIncCombo
MAKE_USER_RECV_PACKET_FLAG(User_OnRequestDecCombo, 0x1CF); //UserLocal::RequestDecCombo
MAKE_USER_RECV_PACKET_FLAG(User_OnRequestSetBlessOfDarkness, 0x1D0); //UserLocal::RequestSetBlessOfDarkness
MAKE_USER_RECV_PACKET_FLAG(User_OnBroadcastOneTimeActionToSplit, 0x1D8); //UserLocal::BroadcastOneTimeActionToSplit
MAKE_USER_RECV_PACKET_FLAG(User_OnBroadcastAffectedEffectToSplit, 0x1D9); //UserLocal::BroadcastAffectedEffectToSplit
MAKE_USER_RECV_PACKET_FLAG(User_OnTempestBladesAttack, 0x1E9); //
MAKE_USER_RECV_PACKET_FLAG(User_OnSetOffPacketForTrinity, 0x1ED); //UserLocal::SendSetOffPacketForTrinity
MAKE_USER_RECV_PACKET_FLAG(User_OnMobZoneStateChangeRequest, 0x1FA); //UserLocal::SendMobZoneStateChangeRequest
MAKE_USER_RECV_PACKET_FLAG(User_OnChangeCharacterRequest, 0x204);

MAKE_USER_RECV_PACKET_FLAG(Android_OnOpenShop, 0x218); //Android::OnOpenShop
MAKE_USER_RECV_PACKET_FLAG(Android_DoActionSe, 0x272); //Android::DoActionSe

MAKE_USER_RECV_PACKET_FLAG(User_OnCheckNpcSpeechQuest, 0x219); //UserLocal::CheckNpcSpeechQuest
MAKE_USER_RECV_PACKET_FLAG(User_OnResetAddSkill, 0x227); //AddAttackAfterSkill::ResetAddSkill

MAKE_USER_RECV_PACKET_FLAG(User_OnPetMove, 0x252);
MAKE_USER_RECV_PACKET_FLAG(User_OnPetAction, 0x253);
MAKE_USER_RECV_PACKET_FLAG(User_OnPetActionSpeak, 0x254);

MAKE_USER_RECV_PACKET_FLAG(AttendanceUI_OpenAttendanceUI, 0x29E); //AttendanceUIMan::OpenAttendanceUI
MAKE_USER_RECV_PACKET_FLAG(User_OnUpdateGoToStarPlanet, 0x2AE); //UserLocal::UpdateGoToStarPlanet
MAKE_USER_RECV_PACKET_FLAG(User_OnDamaged_BattlePvP, 0x31D); //UserLocal::SetDamaged_BattlePvP
MAKE_USER_RECV_PACKET_FLAG(User_OnLand, 0x337); //UserLocal::OnLand
MAKE_USER_RECV_PACKET_FLAG(User_OnStartGatherRequest, 0x3B8); //UserLocal::GatherRequest
MAKE_USER_RECV_PACKET_FLAG(User_OnEndGatherRequest, 0x3B9); //UserLocal::GatherRequest

MAKE_USER_RECV_PACKET_FLAG(BattleRecord_RequestOnCalc, 0x483);//BattleRecordMan::RequestOnCalc

/*MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
MAKE_USER_RECV_PACKET_FLAG(User_, ); //UserLocal::
*/
FLAG_COLLECTION_BODY_END		
#endif